import React, { useEffect } from 'react';
import { ArrowLeft, BookOpen, ChevronRight, Globe2, ShieldCheck, Sparkles, Vote } from 'lucide-react';
import { setPageSeo } from '../seo';

export interface SeoPageData {
  title: string;
  description: string;
  eyebrow: string;
  paragraphs: string[];
  bullets: string[];
}

export const SEO_PAGES: Record<string, SeoPageData> = {
  '/request': { title: 'Request a Profile Review - 1v1Vote', description: 'Request a correction or profile review for the 1v1Vote directory.', eyebrow: 'Profile request', paragraphs: ['If an important public figure is missing or a profile needs a correction, send the exact name, source page, and image source to the administrator for review.', 'Standalone YouTube channels are not added as person profiles.'], bullets: ['Request a missing person', 'Suggest a source correction', 'Suggest a real image', 'Admin review required'] },
  '/about': { title: 'About 1v1Vote - Public Opinion Rankings', description: 'Learn how 1v1Vote ranks public figures through transparent daily voting.', eyebrow: 'About 1v1Vote', paragraphs: ['1v1Vote is a public opinion index for notable people from Pakistan and around the world. Visitors can support one profile every 24 hours and watch the ranking change live.', 'Profiles are curated from reliable public sources, and the site is designed to keep the vote simple, transparent, and easy to share.'], bullets: ['One vote per profile every 24 hours', 'No account required for public voting', 'Source-linked profiles with real images', 'Rankings update as votes arrive'] },
  '/how-it-works': { title: 'How 1v1Vote Works - Daily Public Figure Voting', description: 'Understand the 1v1Vote daily voting and ranking system.', eyebrow: 'How it works', paragraphs: ['Search a person by name or rank, open a profile, and vote. The server records the vote and enforces the 24-hour cooldown for that profile and device.', 'The public list is sorted by total votes first, then shares, then name. This makes the ranking predictable and easy to understand.'], bullets: ['Search names, categories, countries, or ranks', 'Open a dedicated profile page', 'Vote once every 24 hours', 'Share a profile with its own SEO-friendly URL'] },
  '/rankings': { title: 'Live Public Figure Rankings - 1v1Vote', description: 'See the live ranking of important public figures on 1v1Vote.', eyebrow: 'Live rankings', paragraphs: ['The rankings page is the public index of current support. It includes political leaders, religious scholars, athletes, entertainers, business leaders, and other important public figures.', 'Use the search field to jump directly to rank 1, rank 2, rank 32, rank 33, or any other available position.'], bullets: ['Live vote totals', 'Country and category filters', 'Rank-aware search', 'Daily voting cooldown'] },
  '/people': { title: 'Important People Directory - 1v1Vote', description: 'Browse important public figures, leaders, scholars, athletes, and entertainers.', eyebrow: 'People directory', paragraphs: ['Browse the complete public-figure directory and open a profile for background, source links, and voting. The directory excludes incomplete records and standalone YouTube channel pages.', 'Every active profile is kept backed by the persistent application database.'], bullets: ['Pakistan, India, USA, and global profiles', 'Public-source biographies', 'Real profile images', 'Dedicated shareable URLs'] },
  '/vote': { title: 'Vote for Public Figures | 1v1Vote', description: 'Support public figures you follow and help shape the live 1v1Vote ranking. Vote once every 24 hours with no account required.', eyebrow: 'Cast a vote', paragraphs: ['Voting on 1v1Vote is intentionally lightweight. Pick a profile, press the vote button, and return after the cooldown if you want to support that person again.', 'Votes are stored server-side rather than only in the browser, so a deployment does not reset the public ranking.'], bullets: ['Server-side vote records', 'One vote per profile per 24 hours', 'No login required', 'Live totals after each successful vote'] },
  '/discover': { title: 'Discover Public Figures - 1v1Vote', description: 'Discover important people from reliable public sources on 1v1Vote.', eyebrow: 'Discover', paragraphs: ['The discovery workflow researches public-source pages, verifies profile images, rejects non-person articles, and skips duplicates before publishing a profile.', 'The automated workflow is deliberately conservative. An incomplete candidate is better left unpublished than shown as a misleading profile.'], bullets: ['Person-page validation', 'Image URL validation', 'Duplicate protection', 'Admin archive and restore controls'] },
  '/profiles': { title: 'Public Figure Profiles - 1v1Vote', description: 'Open detailed 1v1Vote profile pages for notable people.', eyebrow: 'Profiles', paragraphs: ['Each active person has a dedicated URL with a title, description, image, biography, source link, vote action, and structured metadata for search engines.', 'Profile pages are designed to work as direct landing pages when someone searches for a person and 1v1Vote.'], bullets: ['Name-based SEO titles', 'Open Graph sharing metadata', 'Person structured data', 'Direct vote and share actions'] },
  '/sources': { title: 'Profile Sources - 1v1Vote', description: 'Read how 1v1Vote sources and verifies public-figure profiles.', eyebrow: 'Sources', paragraphs: ['Profiles use public reference pages such as Wikipedia and other reliable public URLs. The source link is shown on the profile so visitors can inspect the reference themselves.', 'Source research does not replace editorial review. The admin panel can correct, archive, restore, or replace any profile.'], bullets: ['Visible source links', 'Image checks before publication', 'Duplicate and article-type filters', 'Admin correction workflow'] },
  '/editorial-policy': { title: 'Editorial Policy - 1v1Vote', description: 'Read the profile quality and editorial policy used by 1v1Vote.', eyebrow: 'Editorial policy', paragraphs: ['1v1Vote publishes profiles for real, notable public figures. It does not publish empty records, placeholder images, standalone channels, or generic organization and event pages.', 'A profile can be archived without destroying its vote and audit history.'], bullets: ['Real people only', 'No placeholder images', 'No standalone channel pages', 'Archived records remain recoverable'] },
  '/data-safety': { title: 'Data Safety - 1v1Vote', description: 'Learn how 1v1Vote protects votes, profiles, and deployment data.', eyebrow: 'Data safety', paragraphs: ['Production data is stored in a managed Turso database and mirrored to the application data directory. The server also makes scheduled backups and a backup on shutdown.', 'Deployment code cannot replace the production database with seed data. Schema normalization merges missing seed records without deleting user-created data.'], bullets: ['Turso is authoritative in production', 'Atomic state writes', 'Scheduled backups', 'Soft archive instead of destructive profile deletion'] },
  '/privacy': { title: 'Privacy Policy - 1v1Vote', description: 'Read the 1v1Vote privacy overview.', eyebrow: 'Privacy', paragraphs: ['1v1Vote uses a server cookie to enforce the public 24-hour voting rule. The cookie is not a public profile and no account is required to vote.', 'Analytics and advertising are currently paused. The site does not display AdSense units while the product is being completed.'], bullets: ['No public profile required', 'Visitor vote identity stored in a cookie', 'Advertising paused', 'Source links open in a new tab'] },
  '/terms': { title: 'Terms of Use - 1v1Vote', description: 'Read the terms for using 1v1Vote.', eyebrow: 'Terms of use', paragraphs: ['1v1Vote is an entertainment and public-opinion website. Rankings represent recorded visitor votes and should not be treated as an official poll, endorsement, or factual measure of merit.', 'Do not abuse the service, submit misleading profile information, or attempt to bypass voting limits.'], bullets: ['Use the site lawfully', 'Do not manipulate votes', 'Respect public-source attribution', 'Contact the admin for corrections'] },
  '/faq': { title: '1v1Vote FAQ - Public Figure Voting Questions', description: 'Answers to common questions about 1v1Vote voting, rankings, and profiles.', eyebrow: 'FAQ', paragraphs: ['You can vote without an account. A device identity cookie and server-side record keep a profile from receiving repeated votes inside the 24-hour window.', 'If a profile has a wrong image or biography, the admin can edit or archive it from the protected admin panel.'], bullets: ['Why can I not vote again? The 24-hour cooldown is active.', 'How do I search rank 33? Enter 33, #33, or rank 33.', 'Can I request a correction? Use the contact route.', 'Are ads active? No, advertising is paused.'] },
  '/contact': { title: 'Contact 1v1Vote - Profile Corrections', description: 'Contact 1v1Vote about profile corrections and source information.', eyebrow: 'Contact', paragraphs: ['For profile corrections, missing images, source changes, or removal requests, contact the site administrator through the project support channel.', 'Include the exact profile URL and the correction you want reviewed.'], bullets: ['Profile image corrections', 'Biography corrections', 'Source link corrections', 'Archive requests'] },
  '/pakistan': { title: 'Pakistani Public Figures - 1v1Vote', description: 'Explore Pakistani politicians, scholars, athletes, and notable public figures.', eyebrow: 'Pakistan', paragraphs: ['Explore the Pakistan section for leading political figures, religious scholars, athletes, and cultural personalities represented in the live public ranking.', 'Use the directory search to find a name or enter a rank number.'], bullets: ['Pakistan country filter', 'Religious scholars', 'Political leaders', 'Important public personalities'] },
  '/india': { title: 'Indian Public Figures - 1v1Vote', description: 'Explore Indian political, sports, and entertainment figures.', eyebrow: 'India', paragraphs: ['The India section brings important Indian public figures into the same transparent live ranking system.', 'Profiles are presented as people rather than standalone channels or generic organization pages.'], bullets: ['India country filter', 'Sports figures', 'Political leaders', 'Entertainment figures'] },
  '/usa': { title: 'American Public Figures - 1v1Vote', description: 'Explore American business, entertainment, sports, and public figures.', eyebrow: 'USA', paragraphs: ['The USA section includes notable people from business, entertainment, sports, and public life.', 'Each profile is source-linked and can be opened directly from search.'], bullets: ['USA country filter', 'Business leaders', 'Entertainment figures', 'Sports figures'] },
  '/global': { title: 'Global Public Figures - 1v1Vote', description: 'Explore global public figures and international leaders.', eyebrow: 'Global', paragraphs: ['The global section highlights internationally recognized people whose public influence reaches beyond one country.', 'The ranking is determined by visitor votes, not by an editorial popularity claim.'], bullets: ['Global country filter', 'International athletes', 'Global entertainers', 'Public-source profiles'] },
  '/politics': { title: 'Political Leaders - 1v1Vote', description: 'Browse political leaders and public officials on the live 1v1Vote ranking.', eyebrow: 'Politics', paragraphs: ['The politics category is for notable political leaders and public figures with reliable public profiles.', 'Political profiles are presented for public voting and information, not as endorsements.'], bullets: ['Politics category filter', 'Source-linked biographies', 'Daily public voting', 'Neutral ranking display'] },
  '/religious-scholars': { title: 'Religious Scholars - 1v1Vote', description: 'Browse religious scholars and Islamic public figures on 1v1Vote.', eyebrow: 'Religious scholars', paragraphs: ['The religious scholars category includes notable scholars and public religious figures with source-backed profiles.', 'Images and biographies can be corrected through the protected admin workflow.'], bullets: ['Religious Scholar category', 'Real images only', 'Biography and source link', 'Archive and restore support'] },
  '/sports': { title: 'Sports Figures - 1v1Vote', description: 'Browse athletes and sports figures on the live public ranking.', eyebrow: 'Sports', paragraphs: ['The sports category includes prominent athletes and sports personalities from Pakistan, India, the USA, and around the world.', 'Search by name or rank to open a direct profile page.'], bullets: ['Sports category filter', 'Live votes', 'Profile source links', 'Shareable URLs'] },
  '/entertainment': { title: 'Entertainment Figures - 1v1Vote', description: 'Browse actors, musicians, and entertainment figures on 1v1Vote.', eyebrow: 'Entertainment', paragraphs: ['The entertainment category includes important actors, musicians, and public entertainment personalities.', 'Standalone YouTube channels are not treated as person profiles.'], bullets: ['Entertainment category filter', 'Source-backed profiles', 'Real image validation', 'Direct profile pages'] },
  '/business': { title: 'Business Leaders - 1v1Vote', description: 'Browse business leaders and entrepreneurs on the live 1v1Vote ranking.', eyebrow: 'Business', paragraphs: ['The business category includes prominent founders, executives, and business leaders with reliable public profiles.', 'Ranking support is based on visitor votes and is updated live.'], bullets: ['Business category filter', 'Global coverage', 'Name and rank search', 'Shareable profile pages'] },
  '/public-figures': { title: 'Public Figures Directory - 1v1Vote', description: 'Browse the complete directory of important public figures.', eyebrow: 'Public figures', paragraphs: ['The public figures directory brings the main categories together in one searchable live index.', 'Open any person page to read the biography, inspect the source, and vote.'], bullets: ['Important people only', 'Search by name or rank', 'Source-linked profiles', 'Live vote totals'] },
  '/leaders': { title: 'Leaders and Public Voices - 1v1Vote', description: 'Explore political, religious, business, and cultural leaders.', eyebrow: 'Leaders', paragraphs: ['Explore notable leaders and public voices represented in the 1v1Vote index.', 'The site separates profile identity from social-media channel ownership.'], bullets: ['Political leaders', 'Religious scholars', 'Business leaders', 'Public-source biographies'] },
  '/scholars': { title: 'Scholars Directory - 1v1Vote', description: 'Explore religious scholars and academic public figures.', eyebrow: 'Scholars', paragraphs: ['The scholars directory focuses on real people with public biographies and reliable source links.', 'Missing or incorrect images can be corrected by an authenticated admin.'], bullets: ['Real person profiles', 'Image verification', 'Detailed biography field', 'Archive protection'] },
  '/athletes': { title: 'Athletes Directory - 1v1Vote', description: 'Explore athletes and sports personalities in the live ranking.', eyebrow: 'Athletes', paragraphs: ['The athletes directory highlights prominent sports personalities and their live public support.', 'Rankings are driven by votes rather than a fixed editorial order.'], bullets: ['Sports profiles', 'Rank-aware search', 'Daily votes', 'Direct profile URLs'] },
  '/actors': { title: 'Actors and Entertainers - 1v1Vote', description: 'Explore actors and entertainers with public profile pages.', eyebrow: 'Actors', paragraphs: ['The entertainment directory includes important actors and entertainers with source-backed identity pages.', 'Standalone channels and generic media pages are excluded from the person directory.'], bullets: ['Entertainment profiles', 'Real images', 'Source links', 'Shareable pages'] },
  '/entrepreneurs': { title: 'Entrepreneurs Directory - 1v1Vote', description: 'Explore entrepreneurs and business leaders on 1v1Vote.', eyebrow: 'Entrepreneurs', paragraphs: ['The entrepreneurs directory is for recognizable founders, executives, and business leaders.', 'Each profile can be ranked, shared, and opened directly from search.'], bullets: ['Business category', 'Global public figures', 'Live support index', 'Structured profile metadata'] },
  '/pakistani-leaders': { title: 'Pakistani Leaders - 1v1Vote', description: 'Explore important Pakistani political and public leaders.', eyebrow: 'Pakistani leaders', paragraphs: ['This directory focuses on important Pakistani leaders and public figures, including political and religious voices.', 'Profiles are shown as people, with biographies and public source links.'], bullets: ['Pakistan filter', 'Politics category', 'Religious scholars', 'Profile corrections'] },
  '/pakistani-scholars': { title: 'Pakistani Scholars - 1v1Vote', description: 'Explore Pakistani religious scholars and public scholars.', eyebrow: 'Pakistani scholars', paragraphs: ['Explore Pakistani scholars whose public work and biographies are documented in reliable sources.', 'The directory does not publish an empty or image-less profile.'], bullets: ['Source-backed identity', 'Real image requirement', 'Daily voting', 'Admin review'] },
  '/international-stars': { title: 'International Public Figures - 1v1Vote', description: 'Explore globally recognized athletes, entertainers, and leaders.', eyebrow: 'International stars', paragraphs: ['International profiles bring globally recognized people into a single searchable support index.', 'Use the dedicated profile link when sharing a person with others.'], bullets: ['Global coverage', 'Sports and entertainment', 'Business leaders', 'SEO-friendly profile pages'] },
  '/vote-guide': { title: '1v1Vote Voting Guide', description: 'A clear guide to voting, cooldowns, rankings, and profile pages.', eyebrow: 'Voting guide', paragraphs: ['Choose a profile, vote once, and return after 24 hours. Your vote contributes to the live public ranking.', 'Rank numbers can be searched directly, so entering 1, 2, 32, or 33 jumps to the matching position.'], bullets: ['Search rank numbers', 'Vote once per profile daily', 'Votes stored server-side', 'Share a person page'] },
  '/categories': { title: 'Public Figure Categories - 1v1Vote', description: 'Browse the public figure categories available on 1v1Vote.', eyebrow: 'Categories', paragraphs: ['The directory groups people into politics, religious scholars, sports, entertainment, business, creators, and public figures.', 'Categories are used for discovery and do not change the underlying vote rules.'], bullets: ['Politics', 'Religious scholars', 'Sports', 'Entertainment and business'] },
  '/country-rankings': { title: 'Country Rankings - 1v1Vote', description: 'Browse public figure rankings by country and region.', eyebrow: 'Country rankings', paragraphs: ['Country filters make it easier to explore Pakistan, India, the USA, and global profiles in one live directory.', 'A person can be globally important while still being connected to a specific country filter.'], bullets: ['Pakistan', 'India', 'USA', 'Global'] },
  '/daily-vote': { title: 'Daily Vote on 1v1Vote', description: 'Return every day to support the public figures you follow.', eyebrow: 'Daily vote', paragraphs: ['The 24-hour vote window lets the ranking reflect continuing public interest without requiring an account.', 'The server records each vote and preserves totals across deployments.'], bullets: ['24-hour reset', 'Server-side protection', 'Live ranking changes', 'No login required'] },
  '/profile-corrections': { title: 'Profile Corrections - 1v1Vote', description: 'Learn how image, biography, and source corrections are handled.', eyebrow: 'Corrections', paragraphs: ['A profile with a missing image, wrong source, or incomplete biography can be corrected by an authenticated administrator.', 'Archiving hides a profile from the public directory without erasing votes or audit history.'], bullets: ['Replace an image', 'Edit biography', 'Change a source URL', 'Archive or restore a profile'] },
  '/site-map': { title: '1v1Vote Site Map', description: 'Browse the public pages and directories available on 1v1Vote.', eyebrow: 'Site map', paragraphs: ['The site map links the public rankings, educational pages, category directories, country pages, and individual profile pages.', 'Every public profile page has its own title and source-aware metadata.'], bullets: ['Rankings and voting', 'Categories and countries', 'Profile pages', 'Data and policy pages'] },
};

export const SeoContentPage: React.FC<{ page: SeoPageData }> = ({ page }) => {
  const path = window.location.pathname.replace(/\/$|^$/, '') || '/';
  useEffect(() => setPageSeo(page.title, page.description, path), [page, path]);
  useEffect(() => {
    const layout = /privacy|terms|data-safety|editorial-policy/.test(path) ? 'policy' : /faq|how-it-works|vote-guide|daily-vote/.test(path) ? 'guide' : /people|rankings|public-figures|country-rankings|categories/.test(path) ? 'directory' : 'editorial';
    document.body.dataset.seoLayout = layout;
    return () => { delete document.body.dataset.seoLayout; };
  }, [path]);
  return <main className="min-h-screen bg-[#060a13] px-4 py-8 text-slate-100 sm:px-6 sm:py-14"><div className="mx-auto max-w-4xl"><a href="/" className="inline-flex items-center gap-2 text-xs font-bold text-sky-300 hover:text-white"><ArrowLeft className="h-4 w-4" /> Back to live rankings</a><section className="mt-8 rounded-[2rem] border border-sky-500/20 bg-gradient-to-br from-[#0d1b36] to-[#0a0e19] p-6 shadow-2xl sm:p-10"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.2em] text-sky-300"><BookOpen className="h-4 w-4" /> {page.eyebrow}</div><h1 className="mt-4 text-3xl font-black tracking-tight text-white sm:text-5xl">{page.title}</h1><p className="mt-5 max-w-3xl text-base leading-8 text-slate-300">{page.description}</p></section><div className="mt-6 grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><article className="rounded-3xl border border-slate-800 bg-[#0b1221] p-6 sm:p-8">{page.paragraphs.map((paragraph) => <p key={paragraph} className="mb-5 text-sm leading-8 text-slate-300 last:mb-0">{paragraph}</p>)}</article><aside className="rounded-3xl border border-slate-800 bg-[#0b1221] p-6"><div className="flex items-center gap-2 text-sm font-black text-white"><Sparkles className="h-4 w-4 text-amber-300" /> Key points</div><ul className="mt-5 space-y-4">{page.bullets.map((bullet) => <li key={bullet} className="flex gap-3 text-sm leading-6 text-slate-400"><ChevronRight className="mt-1 h-4 w-4 shrink-0 text-sky-300" />{bullet}</li>)}</ul></aside></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><a href="/people" className="rounded-2xl border border-slate-800 bg-[#0b1221] p-4 text-sm font-bold text-white hover:border-sky-500/50"><Globe2 className="mb-3 h-5 w-5 text-sky-300" />Browse people</a><a href="/how-it-works" className="rounded-2xl border border-slate-800 bg-[#0b1221] p-4 text-sm font-bold text-white hover:border-sky-500/50"><Vote className="mb-3 h-5 w-5 text-emerald-300" />How voting works</a><a href="/data-safety" className="rounded-2xl border border-slate-800 bg-[#0b1221] p-4 text-sm font-bold text-white hover:border-sky-500/50"><ShieldCheck className="mb-3 h-5 w-5 text-amber-300" />Data safety</a></div></div></main>;
};
